# Generated by Django 3.1.3 on 2020-11-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_auto_20201129_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
