# Generated by Django 3.1.3 on 2020-11-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_auto_20201129_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
